# Generated by Django 4.2.4 on 2023-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Category1", "Category1"),
                    ("Category2", "Category2"),
                    ("Category3", "Category3"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
